[theme]
# The preset Streamlit theme that your custom theme inherits from.
base="dark"

# Primary accent color for interactive elements.
primaryColor="#4A90E2"  # A modern blue accent

# Background color for the main content area.
backgroundColor="#0E1117"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#262730"

# Color used for almost all text.
textColor="#FAFAFA"

# Font family for all text in the app.
# "sans serif", "serif", or "monospace" are the supported options.
font="sans serif"